urls:
    - https://shopee.co.id/POCO-Official-Poco-F5-(12GB-7GB-256GB)-(8GB-5GB-256GB)-Snapdragon-7-Gen-2-5G-120Hz-AMOLED-67W-Triple-Kamera-64MP-OIS-NFC-i.885639549.23548947448
    - https://shopee.co.id/Official-Xiaomi-POCO-F5-(12GB-7GB-256GB)-(8GB-5GB-256GB)-Snapdragon-7-Gen-2-5G-120Hz-AMOLED-67W-Triple-Kamera-64MP-OIS-NFC-i.51925611.23373474285
